labs11-library/labs11-library-FE

package.json
src/App.js
yarn.lock

front end talking to backend, did a simple user get in app

front end talking to backend, did a simple user get in app

---

README.md
package.json
src/App.js
yarn.lock

Initial setup of front end app complete, did a simple get on app to render users from backend

Initial App setup complete, app retrieving data from backend

---

src/App.js
src/components/CheckedOutList.js
src/components/InventoryList.js
src/components/NavBar.js
src/components/UserProfile.js

Added basic pages and navbar

---

src/components/BookDetails.js
src/components/BookList.js
src/data.js

Added fields to data, render to book details
Styled BookDetails.js
Added filter by dropdown using material ui

Added data and styled BookDetails.js

---

.gitignore
package.json
src/App.js
src/components/BookDetails.js
src/components/BookList.js
src/components/ChatApp.js
yarn.lock

chat component and routes initial setup complete

chat component and routes initial setup complete

---

src/App.js

added userId to localStorage

---

src/App.js
src/components/AddBook/AddBook.js
src/components/AddBook/BookSearch.js
src/components/Auth.js
src/components/BookDetails.js
src/components/ChatApp.js
src/components/InventoryList.js
src/components/Login.js
src/components/Mapview.js
src/components/NavBar.js
src/components/SendGrid.js
src/components/Signup.js
src/components/SingleBook.js
src/components/SingleCheckedOutBook.js
src/components/SingleInventory.js
src/redux/actions.js
src/redux/reducers.js
src/url.js

Renders, redirects, and backendBaseUrl

Renders, redirects, and backendBaseUrl

---

src/components/Books/BookDetails.js
src/components/Books/SingleBook.js
src/components/Chat/ChatApp.js
src/url.js

Dynamic chat rooms from /books/:bookid

Local chat

---

src/url.js

Change baseUrl

---

src/App.js
src/components/AddBook/AddBook.js
src/components/Books/SingleBook.js
src/components/CheckedOut/SingleCheckedOutBook.js
src/components/Inventory/InventoryDetails.js
src/components/Inventory/SingleInventoryDetails.js
src/components/Inventory/SingleInventoryWrapper.js
src/components/Layout/LandingPage.js

Chat app renders, App.js clean

Chat app renders, App.js clean

---

src/components/Profile/MyLibrary.js
src/components/Profile/ProfileNavBar.js
src/components/Requests/RequestDetails.js
src/components/Requests/RequestList.js
src/components/Requests/SingleRequest.js

Requests progress

---

src/components/Books/SingleBook.js
src/components/Chat/ChatApp.js
src/components/Profile/MyLibrary.js
src/components/Requests/RequestDetails.js
src/components/Requests/RequestList.js
src/components/Requests/SingleRequest.js
src/redux/actions/checkoutActions.js
src/redux/reducers/checkoutReducers.js

RequestList rendering at /library/requests
Request chat works dynamically
Delete checkoutrequest works

Request progress

---

src/components/Requests/RequestDetails.js
src/components/Requests/RequestList.js
src/redux/actions/checkoutActions.js
src/redux/reducers/checkoutReducers.js

Confirm checkout PUTs available to false

Confirm checkout PUTs available to false

---

src/components/CheckedOut/CheckedOutBookDetails.js
src/components/CheckedOut/CheckedOutList.js

CheckoutDetails render lenderBorrowerName

CheckoutDetails render lenderBorrowerName

---

src/components/Chat/ChatApp.js
src/components/CheckedOut/CheckedOutBookDetails.js
src/components/CheckedOut/CheckedOutList.js
src/components/CheckedOut/SingleCheckedOutBook.js
src/components/Inventory/SingleInventoryDetails.js
src/components/Inventory/SingleInventoryWrapper.js
src/components/Profile/MyLibrary.js

CheckOutList and SingleCheckOut changes

---

src/components/Inventory/InventoryDetails.js
src/url.js

Changed baseUrl

---

src/App.js
src/components/Books/BookDetails.js
src/components/Books/SingleBook.js
src/components/Books/styles.js
src/components/CheckedOut/CheckedOutBookDetails.js
src/components/CheckedOut/CheckedOutList.js
src/components/Email/SendGrid.js
src/components/Inventory/InventoryDetails.js
src/components/Inventory/SingleInventoryDetails.js
src/components/Layout/LandingPage.js
src/components/Layout/NavBar.js
src/components/Layout/styled.js
src/components/Profile/MyLibrary.js
src/components/Profile/ProfileNavBar.js
src/components/Profile/styled.js
src/components/Requests/RequestDetails.js
src/components/Requests/SingleRequest.js
src/components/ViewLibraries/LibraryDetails.js
src/components/ViewLibraries/SingleLibraryDetails.js

Mobile responsiveness progress

---

src/components/Email/SendGrid.js

Sendgrid working

---

src/components/Books/SingleBook.js
src/components/CheckedOut/SingleCheckedOutBook.js
src/components/Requests/RequestDetails.js

Sendgrid v2

---

src/App.js
src/components/Books/SingleBook.js
src/components/CheckedOut/CheckedOutBookDetails.js
src/components/CheckedOut/CheckedOutList.js
src/components/Profile/MyLibrary.js
src/components/Requests/RequestDetails.js
src/redux/actions/checkoutActions.js
src/redux/actions/inventoryActions.js
src/redux/reducers/bookReducers.js
src/redux/reducers/checkoutReducers.js

Stripe email check

---

src/components/Books/SingleBook.js

Fixed strip conditional v2

---

src/components/Books/SingleBook.js
src/components/CheckedOut/CheckedOutBookDetails.js
src/components/Stripe/Payment.js

Scott vojik

---

src/components/CheckedOut/CheckedOutBookDetails.js

stripe charging working

---

public/index.html
src/App.js
src/components/Books/BookDetails.js
src/components/Books/BookList.js
src/components/Inventory/InventoryList.js
src/components/Layout/NavBar.js
src/components/Map/mapview.css
src/components/MyLibrary/MyLibrary.js
src/components/Styles/AppStyles.js
src/components/Styles/InventoryStyles.js
src/components/Styles/LandingPageStyles.js
src/components/Styles/MyLibraryStyles.js

Margin and mobile styles for LandingPage and MyLibrary

Margin and mobile styles

---

src/components/AddBook/BookSearch.js
src/components/AddBook/SearchedBookTile.js
src/components/CheckedOut/CheckedOutBookDetails.js
src/components/Requests/RequestDetails.js
src/components/Requests/RequestList.js
src/components/Styles/NavBarStyles.js
src/components/Styles/NotificationStyles.js
src/components/Styles/SearchStyles.js

search and checkout requests styled

search and checkout requests styled

---

src/components/AddBook/AddBook.js
src/components/CheckedOut/CheckedOutBookDetails.js
src/components/Inventory/SingleInventoryWrapper.js
src/components/Inventory/UpdateInventoryForm.js
src/components/Map/Mapview.js
src/components/Profile/UpdateUserProfile.js
src/components/Profile/UserProfile.js
src/components/Requests/RequestDetails.js
src/components/Requests/SingleRequest.js

White screen and buttons

---

src/components/Books/SingleBook.js
src/components/CheckedOut/SingleCheckedOutBook.js
src/components/Email/SendGrid.js
src/components/Map/Mapview.js
src/components/Requests/RequestDetails.js

Sendgrid HTML emails with link

Sendgrid HTML emails with link

---

src/components/Books/SingleBook.js
src/components/Chat/ChatApp.js
src/components/CheckedOut/CheckedOutBookDetails.js
src/components/Styles/ChatStyles.js

SingleBook chat styles

---

src/components/Chat/ChatApp.js
src/components/CheckedOut/CheckedOutBookDetails.js
src/components/CheckedOut/SingleCheckedOutBook.js
src/components/Styles/ChatStyles.js

Chat styles and confirm return

Chat styles and confirm return

---

src/components/Books/SingleBook.js
src/components/CheckedOut/SingleCheckedOutBook.js
src/components/Requests/SingleRequest.js

Chat styles for single request

Chat styles for single request

---

src/components/CheckedOut/CheckedOutBookDetails.js
src/redux/actions/checkoutActions.js
src/redux/reducers/checkoutReducers.js

Conditional onClick works on CheckedOutBookDetails

Conditional onClick works on CheckedOutBookDetails

---

src/components/Books/SingleBook.js
src/components/Inventory/DeleteInventory.js
src/components/Inventory/SingleInventoryWrapper.js
src/components/Layout/NavBar.js
src/components/Requests/DeleteRequest.js
src/components/Requests/RequestDetails.js
src/components/Requests/RequestList.js
src/components/Requests/SingleRequest.js
src/components/Stripe/Payment.js
src/components/Styles/NavBarStyles.js
src/components/Styles/NotificationStyles.js
src/redux/reducers/checkoutReducers.js

Feedback changes

---

src/components/CheckedOut/CheckedOutBookDetails.js

Confirm return button shows once again

Confirm return button shows once again

---

src/components/Books/BookDetails.js
src/components/CheckedOut/CheckedOutList.js
src/components/Stripe/Payment.js
src/components/Styles/AppStyles.js
src/components/Styles/InventoryStyles.js
src/components/Styles/LandingPageStyles.js
src/components/Styles/NotificationStyles.js
src/components/Styles/TransactionsStyles.js
src/index.js
src/redux/reducers/checkoutReducers.js

Color tweaks and payment button update

Color tweaks and payment button update

---

src/components/Layout/Landing.js

Fully responsive landing page

---

src/App.js
src/components/AddBook/SearchedBookTile.js
src/components/Books/SingleBook.js
src/components/Books/styles.js
src/components/Layout/Landing.js
src/components/Profile/SingleUserProfileCard.js
src/components/Requests/RequestList.js
src/components/Styles/LandingPageStyles.js
src/components/Styles/UserProfileCardStyles.js
src/components/ViewLibraries/LibraryList.js

Mobile, redirecting, copy tweaks, tooltip

 Mobile, redirecting, copy tweaks, tooltip

---

src/App.js
src/components/Books/BookDetails.js
src/components/Books/BookList.js
src/components/Books/SingleBook.js
src/components/Books/SingleBookMapview.js
src/components/Books/styles.js
src/components/CheckedOut/CheckedOutBookDetails.js
src/components/CheckedOut/CheckedOutList.js
src/components/CheckedOut/SingleCheckedOutBook.js
src/components/Email/SendGrid.js
src/components/Inventory/InventoryDetails.js
src/components/Inventory/InventoryList.js
src/components/Layout/BurgerMenu.js
src/components/Layout/LandingPage.js
src/components/Layout/NavBar.js
src/components/Map/Mapview.js
src/components/Profile/SingleUserProfileCard.js
src/components/Profile/UpdateUserProfile.js
src/components/Profile/UserProfileCard.js
src/components/Requests/DeleteRequest.js
src/components/Requests/RequestDetails.js
src/components/Requests/RequestList.js
src/components/Requests/SingleRequest.js
src/components/Styles/CheckoutStyles.js
src/components/Styles/InventoryStyles.js
src/components/Styles/LandingPageStyles.js
src/components/Styles/NotificationStyles.js
src/components/ViewLibraries/LibraryDetails.js
src/components/ViewLibraries/LibraryList.js
src/index.js

Mobile and copy fixes

---

src/components/Inventory/SingleInventoryDetails.js
src/components/Inventory/SingleInventoryWrapper.js
src/components/Inventory/UpdateInventoryForm.js
src/components/Profile/UpdateUserProfile.js
src/components/Styles/InventoryStyles.js

 Single inventory styles

---

src/App.js
src/components/Books/SingleBook.js
src/components/Layout/BurgerMenu.js
src/components/Layout/NavBar.js
src/components/Profile/ProfileNavBar.js
src/components/Profile/UpdateUserProfile.js
src/components/Requests/RequestDetails.js
src/components/Requests/RequestList.js
src/components/Requests/SingleRequest.js

All messages everything

---

public/index.html
src/App.js
src/components/Auth/Auth.js
src/components/Books/BookList.js
src/components/Books/SingleBook.js
src/components/CheckedOut/SingleCheckedOutBook.js
src/components/Layout/Landing.js
src/components/Requests/RequestDetails.js
src/components/Requests/SingleRequest.js
src/components/Styles/InventoryStyles.js
src/redux/reducers/checkoutReducers.js

Three minor fixes/improvements

Three minor fixes/improvements

---

src/components/Chat/ChatApp.js
src/components/Layout/Landing.js

Chat is back

---

src/components/Chat/ChatApp.js

Changed chat room IDs

---

src/components/Books/SingleBook.js
src/components/Requests/SingleRequest.js

Fixed chat bug in notifications

Fixed chat bug in notifications

---

src/components/Layout/Landing.js

Added video to landing page

---

src/App.js
src/components/Layout/Landing.js
src/components/Layout/Privacy.js
src/components/Layout/Team.js

Added privacy policy
